AllowAgentForwarding no
AllowStreamLocalForwarding no
AllowTcpForwarding no
ClientAliveCountMax 2
ClientAliveInterval 60
Compression no
MaxAuthTries 3
MaxSessions 2
PermitRootLogin no
TCPKeepAlive no
X11Forwarding no
