#!/usr/bin/env bash

state=$1
sleep_type=$2

readonly FILE=/tmp/____battery-status____.dat

if [[ ! -f /sys/class/power_supply/BAT0/energy_now || ! -f /sys/class/power_supply/BAT0/energy_full || ! -f /sys/class/power_supply/ADP0/online ]]; then
    echo "This device doesn't have the battery. Exiting"
    exit 0
fi

now=$(date +'%s')
read energy_now < /sys/class/power_supply/BAT0/energy_now #μWh
read energy_full < /sys/class/power_supply/BAT0/energy_full # μWh
read online < /sys/class/power_supply/ADP0/online

# Convert to mWh
((energy_now = energy_now / 1000))
((energy_full = energy_full / 1000))

if [[ $online == 0 ]]; then
    echo "Running on battery"
else
    echo "Running on power supply"
fi

case $state in
"pre")
    echo "Saving time and battery energy before sleeping. Sleep type: '$sleep_type'."
    echo $now > $FILE
    echo $energy_now >> $FILE
    ;;
"post")
    if [[ ! -f $FILE ]]; then
        echo "'$FILE' is missing. Have you missed the 'pre' call?"
        exit 1
    fi

    exec 3<>$FILE
    read prev <&3
    read energy_prev <&3
    rm $FILE

    time_diff=$((now - prev)) # seconds
    days=$((time_diff / (3600*24)))
    hours=$((time_diff % (3600*24) / 3600))
    minutes=$((time_diff % 3600 / 60))
    echo "Slept for $days days $hours hours $minutes minutes. Sleep type: '$sleep_type'."

    (( energy_diff = energy_now - energy_prev )) # mWh
    (( avg_rate = energy_diff * 3600 / time_diff )) # mW

    energy_diff_percent=$(bc -l <<< "$energy_diff * 100 / $energy_full" | awk '{printf "%.2f", $0}') # %
    avg_rate_percent=$(bc -l <<< "$avg_rate * 100 / $energy_full" | awk '{printf "%.2f", $0}') # %/h
    echo "Battery energy change of $energy_diff_percent% ($energy_diff mWh) at an average rate of $avg_rate_percent%/h ($avg_rate mW)."
    ;;
esac
