name: bluebuild
on:
  schedule:
    - cron:
        "00 06 * * *" # build at 06:00 UTC every day
        # (20 minutes after last ublue images start building)
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

  pull_request:
  workflow_dispatch: # allow manually triggering builds
concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  kinoite-main:
    name: Build kinoite main
    permissions:
      contents: read
      actions: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reusable-build.yml
    with:
      recipe: recipe-kinoite-main.yml
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      SECUREBOOT_PRIVATE_KEY: ${{ secrets.SECUREBOOT_PRIVATE_KEY }}

  kinoite-nvidia:
    name: Build kinoite nvidia
    needs: kinoite-main
    permissions:
      contents: read
      actions: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipe-kinoite-nvidia-open.yml
    uses: ./.github/workflows/reusable-build.yml
    with:
      recipe: ${{ matrix.recipe }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      SECUREBOOT_PRIVATE_KEY: ${{ secrets.SECUREBOOT_PRIVATE_KEY }}

  coreos-main:
    name: Build coreos main
    permissions:
      contents: read
      actions: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reusable-build.yml
    with:
      recipe: recipe-coreos-main.yml
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      SECUREBOOT_PRIVATE_KEY: ${{ secrets.SECUREBOOT_PRIVATE_KEY }}
